### ISSUE TITLE
Better to use a cheap switch-mode 3.3v regulator?

### ISSUE THREAD

**Issue by cottsak** [Hipo/weatherbot#1]
If that 3.3v regulator is linear, which I think it is, it will waste a substantial proportion of the battery's capacity. Using a [cheap switch mode regulator module (it must have an inverter on the board)](http://www.ebay.com/itm/Step-Down-Power-Module-Buck-Converter-9V-12V-19V-To-DC-3-3V-Car-Charger-3A-/222209304328) will likely give your devices many more hours of life when deployed in the field.

**Comment by taylanpince** [comment]
Thanks @cottsak! That's actually what we did in the actual project, but I couldn't find the correct module in Fritzing so the schematic doesn't reflect the proper setup. I'll try to remedy this.
